-- Your SQL goes here
CREATE TABLE collections (
    "chain_id" int4 NOT NULL,
    "slug" varchar(255),
    "collection_id" varchar(255) NOT NULL PRIMARY KEY,
    "collection_type" varchar(255) NOT NULL,
    "creator_address" varchar(255) NOT NULL,
    "royaltie" varchar(255),
    "display_name" varchar(255),
    "website" varchar(255),
    "discord" varchar(255),
    "twitter" varchar(255),
    "icon" varchar(255),
    "banner" varchar(255),
    "collection_name" varchar(255) NOT NULL,
    "description" varchar NOT NULL,
    "supply" int8 NOT NULL,
    "version" int8 NOT NULL,
    "metadata_uri" text NOT NULL,
    "tx" varchar(255),
    "metadata" text NOT NULL,
    "verify" bool NOT NULL DEFAULT false,
    "last_metadata_sync" BIGINT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL
);
